[phases.setup]
nixPkgs = ['nodejs-18_x', 'pnpm']

[phases.install]
cmds = ['pnpm install']

[phases.build]
cmds = [
  'rm -rf packages/database/dist packages/database/node_modules/.cache',
  'pnpm --filter @realestate/database build',
  'pnpm --filter backend build'
]

[start]
cmd = 'cd /app && node apps/backend/dist/apps/backend/src/main.js'
